apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    podGroup: "A"
    minAvailable: "2"
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "1000Mi"
      limits:
        memory: "1000Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    podGroup: "A"
    minAvailable: "2"
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "1000Mi"
      limits:
        memory: "1000Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-3
  labels:
    podGroup: "A"
    minAvailable: "2"
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "1000Mi"
      limits:
        memory: "1000Mi"