# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# nodes:
# - role: control-plane
#   kubeadmConfigPatches:
#   - |
#     kind: InitConfiguration
#     nodeRegistration:
#       kubeletExtraArgs:
#         system-reserved: memory=5Gi
# - role: worker
#   kubeadmConfigPatches:
#   - |
#     kind: JoinConfiguration
#     nodeRegistration:
#       kubeletExtraArgs:
#         system-reserved: memory=4.5Gi
# - role: worker
#   kubeadmConfigPatches:
#   - |
#     kind: JoinConfiguration
#     nodeRegistration:
#       kubeletExtraArgs:
#         system-reserved: memory=4Gi